# Generated by Django 3.2.5 on 2021-09-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
