# Generated by Django 3.2.7 on 2021-09-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('subject', models.CharField(choices=[('English', 'English'), ('Kiswahili', 'Kiswahili'), ('Maths', 'Maths'), ('Chemistry', 'Chemistry'), ('Biology', 'Biology'), ('Physics', 'Physics'), ('C.R.E', 'C.R.E'), ('History and Government', 'History and Government'), ('Geography', 'Geography'), ('Business Studies', 'Business Studies'), ('Agriculture', 'Agriculture')], default='none', max_length=1000)),
                ('time', models.TimeField()),
                ('stream', models.CharField(choices=[('form-one', 'form-one'), ('form-two', 'form-two'), ('form-three', 'form-three'), ('form-four', 'form-four')], default='none', max_length=100)),
                ('teacher', models.CharField(default='none', max_length=100)),
            ],
        ),
    ]
