# Generated by Django 3.2.5 on 2021-09-08 17:44

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('votapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personalinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('gender', models.TextField(max_length=10)),
                ('admno', models.IntegerField(blank=True, null=True)),
                ('parent_contact', models.CharField(max_length=40, null=True)),
                ('user', models.OneToOneField(default='0', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
